import { ChapterVideo } from "../../components/ChapterVideo";

interface Props{step:number}
const VID = (name: string) => `/videos/${name}`;

export default function BrowserExtension({step}:Props){
  return(<div className="be-stage">
    {step===0&&(<div className="be-scene"><div className="be-browser"><div className="be-browser-topbar"><div className="be-browser-dots"><span/><span/><span/></div><div className="be-browser-url">juejin.cn/post/73512...</div></div><div className="be-browser-content"><div className="be-page-h1"/><div className="be-page-p"/><div className="be-page-p be-page-p--short"/></div><div className="be-popup"><div className="be-popup-header">收藏书签</div><div className="be-popup-url">juejin.cn/post/73512...</div><div className="be-popup-tags"><span className="be-popup-tag">React</span><span className="be-popup-tag">状态管理</span></div><div className="be-popup-category">前端 / React 生态</div><div className="be-popup-save"/></div></div><ChapterVideo src={VID("07-01-popup.mp4")} width={1520} height={680} /></div>)}
    {step===1&&(<div className="be-scene"><div className="be-browser"><div className="be-browser-topbar"><div className="be-browser-dots"><span/><span/><span/></div><div className="be-browser-url"/></div><div className="be-browser-content be-browser-content--with-panel"><div className="be-side-panel"><div className="be-sp-search"/><div className="be-sp-list">{[1,2,3,4,5].map(i=><div key={i} className="be-sp-item"><div className="be-sp-item-icon"/><div className="be-sp-item-title">最近收藏的书签 {i}</div></div>)}</div><div className="be-sp-status">当前页面：已收藏 ✓</div></div></div></div><ChapterVideo src={VID("07-02-sidepanel.mp4")} width={1520} height={680} /></div>)}
    {step===2&&(<div className="be-scene"><div className="be-apikey-panel"><div className="be-apikey-header">API Key 管理</div><div className="be-apikey-list"><div className="be-apikey-row"><span className="be-apikey-name">markbox-extension</span><span className="be-apikey-mask">mk_****_a1b2c3</span><span className="be-apikey-revoke">吊销</span></div></div><div className="be-apikey-generate">生成新 Key</div></div><ChapterVideo src={VID("07-04-apikey.mp4")} width={1520} height={680} /></div>)}
    {step===3&&(<div className="be-scene be-scene--auth"><div className="be-auth-diagram"><div className="be-auth-box be-auth-box--ext">浏览器扩展</div><div className="be-auth-line"/><div className="be-auth-split"><div className="be-auth-path"><span className="be-auth-path-label">Cookie 自动认证</span><div className="be-auth-path-dot be-auth-path-dot--cookie"/></div><div className="be-auth-path"><span className="be-auth-path-label">API Key 备用</span><div className="be-auth-path-dot be-auth-path-dot--key"/></div></div><div className="be-auth-box be-auth-box--server">MarkBox 主站</div></div><p className="be-auth-label">双认证——Cookie 自动走 + API Key 手动配</p></div>)}
  </div>);
}
