interface Props{step:number}
export default function Architecture({step}:Props){
  return(<div className="ar-stage">
    {step===0&&(<div className="ar-scene"><div className="ar-stack"><div className="ar-layer ar-layer--fe"><div className="ar-layer-label">前端 · Next.js 16 + React 19 + TypeScript</div><div className="ar-layer-chips"><span>Tailwind CSS</span><span>shadcn/ui</span><span>motion</span></div></div><div className="ar-layer ar-layer--api"><div className="ar-layer-label">API · Next.js Route Handlers + Prisma ORM</div><div className="ar-layer-chips"><span>30+ API Routes</span><span>SQLite</span></div></div><div className="ar-layer ar-layer--data"><div className="ar-layer-label">数据 · 20+ 模型 · Prisma Schema</div><div className="ar-layer-chips"><span>Bookmark</span><span>Tag</span><span>Category</span><span>Collection</span><span>LearningPath</span><span>Annotation</span><span>...</span></div></div><div className="ar-layer ar-layer--ai"><div className="ar-layer-label">AI · DeepSeek V4 Flash</div><div className="ar-layer-chips"><span>分类</span><span>摘要</span><span>推荐</span><span>对比</span><span>学习路径</span></div></div></div></div>)}
    {step===1&&(<div className="ar-scene"><div className="ar-stack"><div className="ar-layer ar-layer--fe ar-layer--lit"><div className="ar-layer-label">前端 · Next.js 16 + React 19 + TypeScript</div><div className="ar-layer-chips"><span>Tailwind CSS</span><span>shadcn/ui</span><span>motion</span></div></div><div className="ar-layer ar-layer--api ar-layer--lit"><div className="ar-layer-label">API · Next.js Route Handlers + Prisma ORM</div><div className="ar-layer-chips"><span>30+ API Routes</span><span>SQLite</span></div></div><div className="ar-layer ar-layer--data ar-layer--lit"><div className="ar-layer-label">数据 · 20+ 模型 · Prisma Schema</div><div className="ar-layer-chips"><span>Bookmark</span><span>Tag</span><span>Category</span><span>...</span></div></div><div className="ar-layer ar-layer--ai ar-layer--lit"><div className="ar-layer-label">AI · DeepSeek V4 Flash</div><div className="ar-layer-chips"><span>贯穿全链路</span></div></div></div><p className="ar-stack-label">四层架构——前端、API、数据、AI 全打通</p></div>)}
    {step===2&&(<div className="ar-scene ar-scene--with-ext"><div className="ar-main-stack"><div className="ar-layer ar-layer--fe ar-layer--sm">前端</div><div className="ar-layer ar-layer--api ar-layer--sm">API</div><div className="ar-layer ar-layer--data ar-layer--sm">数据</div><div className="ar-layer ar-layer--ai ar-layer--sm">AI</div></div><div className="ar-auth-bridge"/><div className="ar-ext-stack"><div className="ar-ext-card"><div className="ar-ext-card-title">MarkBox 扩展</div><div className="ar-ext-card-chips"><span>WXT</span><span>Manifest V3</span><span>Popup</span><span>Side Panel</span><span>Context Menu</span></div></div></div><p className="ar-ext-label">浏览器扩展独立栈——共享认证层</p></div>)}
    {step===3&&(<div className="ar-scene"><div className="ar-er-diagram"><div className="ar-er-box ar-er-box--main">Bookmark</div><div className="ar-er-connector"><div className="ar-er-box ar-er-box--sub">Tag</div><div className="ar-er-box ar-er-box--sub">Category</div><div className="ar-er-box ar-er-box--sub">Collection</div></div><div className="ar-er-connector"><div className="ar-er-box ar-er-box--sub">LearningPath</div><div className="ar-er-box ar-er-box--sub">Annotation</div><div className="ar-er-box ar-er-box--sub">Comparison</div></div></div><p className="ar-er-label">20+ 数据模型——以 Bookmark 为中心的关系网</p></div>)}
    {step===4&&(<div className="ar-scene"><div className="ar-ai-flow"><div className="ar-ai-flow-node">收藏书签</div><div className="ar-ai-flow-arrow">→</div><div className="ar-ai-flow-node">AI 分类</div><div className="ar-ai-flow-arrow">→</div><div className="ar-ai-flow-node">摘要生成</div><div className="ar-ai-flow-arrow">→</div><div className="ar-ai-flow-node">关联推荐</div><div className="ar-ai-flow-arrow">→</div><div className="ar-ai-flow-node">横向对比</div><div className="ar-ai-flow-arrow">→</div><div className="ar-ai-flow-node">学习路径</div></div><p className="ar-ai-flow-label">一个模型打穿全链路——从收藏到学习路径</p></div>)}
    {step===5&&(<div className="ar-scene ar-scene--quote"><p className="ar-quote">收藏不是目的，能用起来才是。</p><p className="ar-quote-sub">MarkBox · 让每一个收藏都有归属</p></div>)}
    {step===6&&(<div className="ar-scene ar-scene--end"><p className="ar-end-text">谢谢观看</p><div className="ar-end-rule"/></div>)}
  </div>);
}
