import { ChapterVideo } from "../../components/ChapterVideo";

interface Props { step: number }
const VID = (name: string) => `/videos/${name}`;

export default function KnowledgeDiscovery({ step }: Props) {
  return (<div className="kd-stage">
    {step===0&&(<div className="kd-scene kd-scene--graph"><div className="kd-graph-canvas"><div className="kd-stars"/><div className="kd-node kd-node--cat" style={{top:'30%',left:'20%'}}><span className="kd-node-label">前端</span></div><div className="kd-node kd-node--cat" style={{top:'25%',left:'55%'}}><span className="kd-node-label">后端</span></div><div className="kd-node kd-node--cat" style={{top:'55%',left:'40%'}}><span className="kd-node-label">DevOps</span></div><div className="kd-node kd-node--tag" style={{top:'18%',left:'35%'}}><span className="kd-node-label kd-node-label--small">React</span></div><div className="kd-node kd-node--tag" style={{top:'42%',left:'65%'}}><span className="kd-node-label kd-node-label--small">Docker</span></div><div className="kd-node kd-node--tag" style={{top:'60%',left:'22%'}}><span className="kd-node-label kd-node-label--small">AI</span></div><svg className="kd-edges" viewBox="0 0 800 500" preserveAspectRatio="none"><line x1="200" y1="160" x2="520" y2="160" stroke="var(--rule)" strokeWidth="1"/><line x1="520" y1="160" x2="380" y2="300" stroke="var(--rule)" strokeWidth="1"/><line x1="200" y1="160" x2="380" y2="300" stroke="var(--rule)" strokeWidth="1"/></svg></div><p className="kd-graph-label">所有书签、标签、分类——变成一张可交互的星图</p></div>)}
    {step===1&&(<div className="kd-scene kd-scene--graph"><div className="kd-graph-canvas"><div className="kd-stars"/><div className="kd-node kd-node--tag kd-node--active" style={{top:'35%',left:'50%'}}><span className="kd-node-label kd-node-label--small">React</span><div className="kd-node-glow"/></div><div className="kd-node kd-node--bm kd-node--bm-video" style={{top:'15%',left:'30%'}}/><div className="kd-node kd-node--bm kd-node--bm-article" style={{top:'20%',left:'60%'}}/><div className="kd-node kd-node--bm kd-node--bm-repo" style={{top:'50%',left:'75%'}}/><div className="kd-node kd-node--bm kd-node--bm-webpage" style={{top:'55%',left:'20%'}}/><div className="kd-node kd-node--bm kd-node--bm-video" style={{top:'60%',left:'45%'}}/></div><ChapterVideo src={VID("04-01-graph-click.mp4")} width={1520} height={680} /></div>)}
    {step===2&&(<div className="kd-scene"><div className="kd-timeline-demo"><div className="kd-timeline-header"><div className="kd-tl-play"/><div className="kd-tl-speed">1x</div><div className="kd-tl-count">可见节点：47</div></div><div className="kd-timeline-track"><div className="kd-tl-range" style={{width:'65%'}}/><div className="kd-tl-thumb" style={{left:'65%'}}/></div><div className="kd-tl-labels"><span>2024.01</span><span>2025.01</span><span>2026.06</span></div></div><ChapterVideo src={VID("04-02-graph-timeline.mp4")} width={1520} height={680} /></div>)}
    {step===3&&(<div className="kd-scene"><div className="kd-rec-stack"><div className="kd-rec-tier kd-rec-tier--1"><span className="kd-rec-tier-label">第 1 层 · 标签相似度</span><div className="kd-rec-bar"><div className="kd-rec-bar-fill" style={{width:'90%'}}/></div><span className="kd-rec-stat">&lt;50ms · 零 AI 成本</span></div><div className="kd-rec-tier kd-rec-tier--2"><span className="kd-rec-tier-label">第 2 层 · 语义向量重排</span><div className="kd-rec-bar"><div className="kd-rec-bar-fill kd-rec-bar-fill--ai" style={{width:'75%'}}/></div><span className="kd-rec-stat">DeepSeek Embedding · 余弦相似度</span></div><div className="kd-rec-tier kd-rec-tier--3"><span className="kd-rec-tier-label">第 3 层 · 三维推荐</span><div className="kd-rec-dims"><span className="kd-rec-dim">往深挖</span><span className="kd-rec-dim">往广拓</span><span className="kd-rec-dim">翻旧书签</span></div></div></div><ChapterVideo src={VID("04-03-recommendations.mp4")} width={1520} height={680} /></div>)}
    {step===4&&(<div className="kd-scene"><div className="kd-lp-list"><div className="kd-lp-item"><div className="kd-lp-item-icon"/><div className="kd-lp-item-info"><div className="kd-lp-item-title">系统设计入门</div><div className="kd-lp-item-meta">6 本书签 · 已完成 2/6</div></div><div className="kd-lp-item-progress"><div className="kd-lp-item-progress-fill" style={{width:'33%'}}/></div></div><div className="kd-lp-item kd-lp-item--new"><div className="kd-lp-add-icon"/><span>创建新路径</span></div></div><ChapterVideo src={VID("04-04-learning-path.mp4")} width={1520} height={680} /></div>)}
    {step===5&&(<div className="kd-scene"><div className="kd-ai-analysis"><div className="kd-ai-analysis-header">AI 分析结果 · 系统设计入门</div><div className="kd-ai-analysis-grid"><div className="kd-ai-slot"><label>难度</label><span>中级</span></div><div className="kd-ai-slot"><label>预估时间</label><span>12 小时</span></div><div className="kd-ai-slot"><label>前置知识</label><span>网络基础 · 数据库</span></div><div className="kd-ai-slot"><label>知识缺口</label><span className="kd-ai-gap">分布式一致性 · CAP 定理</span></div></div></div><ChapterVideo src={VID("04-05-ai-analysis.mp4")} width={1520} height={680} /></div>)}
    {step===6&&(<div className="kd-scene"><div className="kd-note-demo"><div className="kd-note-bubble"><div className="kd-note-type kd-note-type--takeaway">心得</div><div className="kd-note-text">CAP 定理在实际系统中的取舍比理论复杂的多...</div></div><div className="kd-note-bubble"><div className="kd-note-type kd-note-type--question">问题</div><div className="kd-note-text">为什么 Google Spanner 能同时满足 CP？</div></div><div className="kd-note-export"><div className="kd-note-export-icon"/><span>导出 Markdown</span></div></div><p className="kd-note-label">三种笔记 + 一键导出 Markdown</p></div>)}
  </div>);
}
