import { ChapterVideo } from "../../components/ChapterVideo";

interface Props{step:number}
const VID = (name: string) => `/videos/${name}`;

export default function ReadingArchive({step}:Props){
  return(<div className="ra-stage">
    {step===0&&(<div className="ra-scene ra-scene--reader"><div className="ra-reader-frame"><div className="ra-reader-content"><div className="ra-reader-h1"/><div className="ra-reader-p"/><div className="ra-reader-p ra-reader-p--mid"/><div className="ra-reader-p ra-reader-p--short"/><div className="ra-reader-p"/><div className="ra-reader-p ra-reader-p--mid"/></div></div><ChapterVideo src={VID("06-01-reader.mp4")} width={1520} height={680} /></div>)}
    {step===1&&(<div className="ra-scene ra-scene--reader"><div className="ra-reader-frame"><div className="ra-reader-content"><div className="ra-reader-h1"/><div className="ra-reader-p"><span className="ra-highlight ra-highlight--yellow">React 状态管理方案的选择将直接影响团队协作效率和长期维护成本。</span></div><div className="ra-highlight-tooltip"><span className="ra-hl-btn ra-hl-btn--yellow"/><span className="ra-hl-btn ra-hl-btn--green"/><span className="ra-hl-btn ra-hl-btn--blue"/><span className="ra-hl-btn ra-hl-btn--red"/></div><div className="ra-reader-p ra-reader-p--mid"/></div></div><ChapterVideo src={VID("06-02-annotation.mp4")} width={1520} height={680} /></div>)}
    {step===2&&(<div className="ra-scene"><div className="ra-note-demo"><div className="ra-note-highlight ra-note-highlight--red">原文没有给出任何数据支持这个结论。</div><div className="ra-note-editor"><div className="ra-note-editor-header">边注 · 红色 · 不认同</div><div className="ra-note-editor-text">这里观点我不同意——文章说 React 有性能问题，但给出的 benchmark 是 2023 年的版本，现在早就修了。</div></div></div><p className="ra-note-label">点击高亮 → 写边注 → 侧边栏汇总</p></div>)}
    {step===3&&(<div className="ra-scene"><div className="ra-anno-panel"><div className="ra-anno-header"><span>批注列表</span><div className="ra-anno-filters"><span className="ra-anno-filter ra-anno-filter--yellow"/><span className="ra-anno-filter ra-anno-filter--green"/><span className="ra-anno-filter ra-anno-filter--blue"/><span className="ra-anno-filter ra-anno-filter--red ra-anno-filter--active"/></div></div><div className="ra-anno-list"><div className="ra-anno-item"><span className="ra-anno-item-dot ra-anno-item-dot--red"/><span className="ra-anno-item-text">"没有数据支持的结论"</span></div></div><div className="ra-anno-export">导出 Markdown 批注</div></div><p className="ra-anno-label">批注面板——按颜色筛选 + Markdown 导出</p></div>)}
    {step===4&&(<div className="ra-scene ra-scene--with-video"><div className="ra-archive-status"><div className="ra-archive-card ra-archive-card--done"><div className="ra-archive-icon ra-archive-icon--done"/><span>已存档 ✓</span><span className="ra-archive-meta">2026-06-15 · 48KB</span></div><div className="ra-archive-card ra-archive-card--pending"><div className="ra-archive-icon ra-archive-icon--pending"/><span>正在存档...</span></div></div><ChapterVideo src={VID("06-03-archive.mp4")} width={1520} height={680} /></div>)}
    {step===5&&(<div className="ra-scene"><div className="ra-health-panel"><div className="ra-health-stats"><div className="ra-health-stat ra-health-stat--healthy"><span className="ra-health-num">120</span><span>正常</span></div><div className="ra-health-stat ra-health-stat--redirect"><span className="ra-health-num">5</span><span>重定向</span></div><div className="ra-health-stat ra-health-stat--broken"><span className="ra-health-num">3</span><span>失效</span></div></div></div><ChapterVideo src={VID("06-04-health.mp4")} width={1520} height={680} /></div>)}
    {step===6&&(<div className="ra-scene"><div className="ra-broken-list"><div className="ra-broken-item"><div className="ra-broken-url">old-blog.example.com/react-hooks</div><div className="ra-broken-status">404</div><div className="ra-broken-date">检测于 2026-06-18</div><div className="ra-broken-archive">查看存档 →</div></div><div className="ra-broken-item"><div className="ra-broken-url">deprecated.lib.example/api-reference</div><div className="ra-broken-status">404</div><div className="ra-broken-date">检测于 2026-06-18</div><div className="ra-broken-archive">查看存档 →</div></div></div><p className="ra-broken-label">失效链接列表——链接死了，知识没丢</p></div>)}
  </div>);
}
