import { ChapterVideo } from "../../components/ChapterVideo";

interface Props{step:number}
const VID = (name: string) => `/videos/${name}`;

export default function AnalysisCompare({step}:Props){
  function getRadarPts(r:number){const cx=200,cy=200,n=5;return Array.from({length:n},(_,i)=>{const a=(Math.PI*2*i)/n-Math.PI/2;return`${cx+r*Math.cos(a)},${cy+r*Math.sin(a)}`}).join(' ')}
  function getRadarAxes(){const cx=200,cy=200,r=90,n=5;return Array.from({length:n},(_,i)=>{const a=(Math.PI*2*i)/n-Math.PI/2;return[cx,cy,cx+r*Math.cos(a),cy+r*Math.sin(a)]as[number,number,number,number]})}
  function getRadarLabelPos(i:number):React.CSSProperties{const cx=200,cy=200,r=115,n=5;const a=(Math.PI*2*i)/n-Math.PI/2;return{position:'absolute',left:cx+r*Math.cos(a),top:cy+r*Math.sin(a),transform:'translate(-50%,-50%)'}}
  return(<div className="ac-stage">
    {step===0&&(<div className="ac-scene ac-scene--with-video"><div className="ac-select-grid"><div className="ac-sel-card ac-sel-card--checked"><div className="ac-sel-check"/><div className="ac-sel-cover"/><div className="ac-sel-title">React 状态管理方案对比</div></div><div className="ac-sel-card ac-sel-card--checked"><div className="ac-sel-check"/><div className="ac-sel-cover"/><div className="ac-sel-title">Vue 3 Composition API 实战</div></div><div className="ac-sel-card ac-sel-card--checked"><div className="ac-sel-check"/><div className="ac-sel-cover"/><div className="ac-sel-title">Svelte 与 React 设计哲学</div></div></div><div className="ac-start-btn">开始对比</div><ChapterVideo src={VID("05-01-compare-select.mp4")} width={1520} height={680} /></div>)}
    {step===1&&(<div className="ac-scene"><div className="ac-radar"><div className="ac-radar-canvas"><svg viewBox="0 0 400 400" className="ac-radar-svg"><defs><radialGradient id="acRadarGrad"><stop offset="0%" stopColor="var(--accent)" stopOpacity="0.15"/><stop offset="100%" stopColor="var(--accent)" stopOpacity="0"/></radialGradient></defs>{[1,2,3].map(r=><polygon key={r} points={getRadarPts(r*30)} fill="none" stroke="var(--rule)" strokeWidth="1"/>)}{getRadarAxes().map(([x1,y1,x2,y2],i)=><line key={i} x1={x1} y1={y1} x2={x2} y2={y2} stroke="var(--rule)" strokeWidth="1"/>)}<polygon points={getRadarPts(75)} fill="url(#acRadarGrad)" stroke="var(--accent)" strokeWidth="2.5"/></svg><div className="ac-radar-labels">{["深度","可读性","权威度","新鲜度","实用性"].map((l,i)=><span key={i} className="ac-radar-label" style={getRadarLabelPos(i)}>{l}</span>)}</div></div></div><p className="ac-radar-title">五维雷达图——谁强谁弱一眼分明</p></div>)}
    {step===2&&(<div className="ac-scene"><div className="ac-matrix-scroll"><table className="ac-matrix"><thead><tr><th>对比维度</th><th>React 状态管理</th><th>Vue 3 实战</th><th>Svelte 哲学</th></tr></thead><tbody><tr><td colSpan={4} className="ac-matrix-section">观点层</td></tr><tr><td>核心主张</td><td>Hooks 是第一公民</td><td>响应式是默认</td><td>编译时优于运行时</td></tr><tr className="ac-matrix-divergent"><td>学习曲线</td><td>中等</td><td className="ac-matrix-highlight">低 ❗</td><td className="ac-matrix-highlight">低 ❗</td></tr><tr><td colSpan={4} className="ac-matrix-section">技术层</td></tr><tr><td>运行时体积</td><td>~45KB</td><td>~33KB</td><td className="ac-matrix-highlight">~8KB ✓</td></tr></tbody></table></div><p className="ac-matrix-label">对比矩阵——分歧高亮，逐条拆开对</p></div>)}
    {step===3&&(<div className="ac-scene"><div className="ac-commentary"><div className="ac-comment-block"><div className="ac-comment-title">观点分布</div><p className="ac-comment-text">三篇文章在"状态管理应简单"上高度一致，但对实现路径分歧明显。</p></div><div className="ac-comment-block"><div className="ac-comment-title">推荐阅读顺序</div><p className="ac-comment-text">Svelte 设计哲学 → React 状态管理 → Vue 3 实战</p></div></div><p className="ac-commentary-label">AI 总结评论——关键分歧 + 推荐顺序</p></div>)}
    {step===4&&(<div className="ac-scene ac-scene--with-video"><div className="ac-dash-grid"><div className="ac-dash-card"><div className="ac-dash-pie"><div className="ac-dash-pie-slice" style={{background:'conic-gradient(var(--accent) 0% 45%, #f59e0b 45% 65%, #10b981 65% 85%, #6b7280 85% 100%)'}}/></div><span>状态分布</span></div><div className="ac-dash-card"><div className="ac-dash-bars"><div className="ac-dash-bar" style={{height:'80%'}}/><div className="ac-dash-bar" style={{height:'55%'}}/><div className="ac-dash-bar" style={{height:'35%'}}/></div><span>分类 Top</span></div><div className="ac-dash-card"><div className="ac-dash-cloud"><span style={{fontSize:'28px'}}>Docker</span><span style={{fontSize:'20px'}}>React</span><span style={{fontSize:'16px'}}>AI</span><span style={{fontSize:'24px'}}>前端</span></div><span>词云</span></div></div><ChapterVideo src={VID("05-03-dashboard.mp4")} width={1520} height={680} /></div>)}
    {step===5&&(<div className="ac-scene"><div className="ac-weekly"><div className="ac-weekly-col ac-weekly-col--this"><div className="ac-weekly-header">本周</div><div className="ac-weekly-stat">新增 15 <span className="ac-weekly-arrow ac-weekly-arrow--up">↑ 12%</span></div><div className="ac-weekly-stat">已读 8 <span className="ac-weekly-arrow ac-weekly-arrow--up">↑ 5%</span></div></div><div className="ac-weekly-col ac-weekly-col--last"><div className="ac-weekly-header">上周</div><div className="ac-weekly-stat">新增 13</div><div className="ac-weekly-stat">已读 7</div></div></div><ChapterVideo src={VID("05-04-weekly-tracking.mp4")} width={1520} height={680} /></div>)}
    {step===6&&(<div className="ac-scene"><div className="ac-hotness-list"><div className="ac-hotness-item"><div className="ac-hotness-repo">facebook/react</div><div className="ac-hotness-stats"><span>★ 235k</span><span>↑ 1.2k</span></div><svg className="ac-sparkline" viewBox="0 0 120 30" preserveAspectRatio="none"><path d="M0,25 Q10,22 20,18 T40,15 T60,10 T80,14 T100,8 T120,5" fill="none" stroke="var(--accent)" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></div><div className="ac-hotness-item"><div className="ac-hotness-repo">tanstack/react-query</div><div className="ac-hotness-stats"><span>★ 42k</span><span>↑ 320</span></div><svg className="ac-sparkline" viewBox="0 0 120 30" preserveAspectRatio="none"><path d="M0,22 Q30,18 60,12 T120,6" fill="none" stroke="var(--accent)" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></div></div><p className="ac-hotness-label">热度追踪——关注 GitHub 仓库 star 走势</p></div>)}
  </div>);
}
